spring:
  application:
    name: accountsservice
  profiles.active: dev

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

---
spring:
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  sql.init.mode: always
  datasource:
    url: "jdbc:h2:mem:accounts_db"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9900

logging:
  path: /var/logs/
  file: /var/logs/accounts.log
  level:
    root: DEBUG

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/accounts_db
    username: account_user
    password: acc123
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true

server:
  servlet.contextPath: /api/v1
  port: 9943

logging:
  path: /var/logs/
  file: /var/logs/accounts.log
  level:
    root: ERROR